### ISSUE TITLE
Create Podcast Promo Recording

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#138]
Theres lots of great tech podcasts out there that would be willing to run a 45-60 second promo for us.  Lets record something brief explaining what SCALE is and why they should come. We can offer a 40% promo code for them to provider their listeners as well.

**Comment by irabinovitch** [comment]
Here are a few examples of the ones  Jason Riker has recorded over the years. We had similar records for SCALE 12x and SCALE 13x, I just don't have them handy at the moment.

SCALE 11x
http://www.socallinuxexpo.org/scale11x-supporting/default/files/promo/scale11x_6c.mp3

SCALE 10x
https://www.socallinuxexpo.org/scale10x-supporting/sites/default/files/promo/scale10x_promo1.mp3

**Comment by geekhunter** [comment]
Larry, if your subscribed to this open issue... ping me at either geekhunter@gmail.com or call me at 626-921-4904 so we can plan for the development of the promos.

**Comment by irabinovitch** [comment]
Adding @lcafiero  here as well.

**Comment by irabinovitch** [comment]
@geekhunter  Were you able to connect?

**Comment by geekhunter** [comment]
Yes, connected and reviewing the promo. I'm sending a few suggestions this
morning and then we'll get to recording.

On Sun, Nov 15, 2015 at 10:46 PM, Ilan Rabinovitch <notifications@github.com

**Comment by geekhunter** [comment]
@lcafiero Sorry for the delay, got hit with a ton of things at work over the last week.

I reviewed the promo copy and really like it. The only suggestion I might have is to find a word to replace "greybeard" that suggests being an "old-timer" but doesn't necessary discount women who have been a part of the movement since the beginning. Having attended a lot of conferences, I have heard from many women who are sensitive to exclusionary terminology or just the assumption that the major contributors are male.

The only other suggestion might be to substitute "Virtualization and Container Technologies" for "Container and Virtualization." This suggestion is made only because it is easier to read and separate clearly from the track right before it... (i.e., "Embedded Linux"). Basically, I think it's just easier to read.

What do you think? We want to be sure to cast a wide open net for our audience and be sensitive to how the message may be received, even if it is totally unintentional.

With regard to recording... I'm here in Los Angeles but I do have a very good USB microphone and have done some recording for librivox books, etc. I could take a stab at recording the promo using some music with a creative commons license for an intro/outro. If you planned on doing the recording, that's fine but I'll have limited ability to help due to our "geographic differences."

Let me know what your thoughts are on the next step so we can get this turned around.

**Comment by irabinovitch** [comment]
@geekhunter We'd be happy to have you give a go at recording/mixing on your end.  What length are we targeting at the moment?

**Comment by irabinovitch** [comment]
@geekhunter  hows the recording going? Would love to get it out to all the podcasts before they break for the holidays.

**Comment by irabinovitch** [comment]
@lcafiero @geekhunter do we think we might have something we can send out this weekend?

**Comment by geekhunter** [comment]
Yes, just finished and would like your input. Total length is 120 seconds. The last samples were 118 and 114 seconds so I hope that is OK. If I need to edit it down, let me know. The link to the files is:

https://drive.google.com/folderview?id=0B7ezZBKwK4d3WndIUUZCZ3RGU1E&usp=sharing

I can't upload to github since it doesn't support .mp3 and .m4a files.

**Comment by geekhunter** [comment]
So far... no feedback on podcast promo. Larry, Ilan, do you have suggestions/comments? What would be next step?

**Comment by lcafiero** [comment]
I think it's fine. If there's no comments, let's just go ahead and go with
it.

**Comment by irabinovitch** [comment]
Thanks Todd! We've submitted this to a number of podcasts.  Appreciate your help!

**Comment by geekhunter** [comment]
NP glad to help out!

TCC
