### ISSUE TITLE
Audience & Topic Tags Point at 13x talks

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#159]
Looks like the audience and topic tags found here:
http://www.socallinuxexpo.org/scale/14x/presentations

Are pointing at just 13x talks.

**Comment by rgolan** [comment]
Phew! That was quite a bit more work than I thought at first. Please check that you are getting the proper results now. I created custom views for both those track and audience lists rather than relying on the built in taxonomy term pages. Now they should work past, present and future SCALE events. I also added the term title at the top of the page. 

These page are not actually limited to showing just presentations but will show anything with that term. Fortunately, we only apply the Track and Audience terms to presentations. If you do find it's still not working as you expect, let me know.

**Comment by garethgreenaway** [comment]
That looks better!  Thanks!
